### ISSUE TITLE
Certain icons can appear multiple times

### ISSUE THREAD

**Issue by laszlostark** [Annosz/UIInfoSuite2#381]
This report is in regards to mod version 2.2.3.0-alpha-2, SMAPI 4.0.1 and game version 1.6.1

Certain icons appear multiple times when you quit the game onto the title screen and then load a save. Once a save has been loaded for the first time, every subsequent time you load a save, there will be an additional set of icons. I have observed the following behavior:

- Only certain notification icons are affected:
  - Blacksmith/Tool upgrade
  - I believe Seasonal Forage (not 100% sure on that one)
  - Queen of Sauce
  - Traveling Cart
  - Daily luck and Birthday notifications are **NOT** affected

- This issue is only resolved by restarting the game. I've tried:
  - Toggling the icons off and on in the UI Info Suite settings
  - Progressing to the next day (Note that icons may disappear on a new day. However, the next time one of the icons that are listed above appears there will be multiple sets of them.)

In fact it doesn't matter if one of the affected icons is present when you quit and reload a save. Once one of the icons appears at the start of a day there will be as many sets of these icons as times you have loaded the save since starting the game.

For reference I have recorded this video:

https://github.com/Annosz/UIInfoSuite2/assets/62555605/009a5244-ed8c-4517-bedc-abe4fd2deeab

Edit: The video playback is kind of broken, idk if that's just the case for me but regardless I uploaded the video to Youtube: https://www.youtube.com/watch?v=Q3svopZwXu4

**Comment by drewhoener** [comment]
@laszlostark This is very interesting, I've never seen this occur! 
To be fair, I usually exit the game upon testing the thing I'm there for, so I probably wouldn't have seen this.
I'm wondering if something has changed behind the screens with the PerScreen logic, I only check for Id == 0. If that's changed, then the icon rows wouldn't unload on return to title.

**Comment by drewhoener** [comment]
> @drewhoener What's weird to me is that not all of the icons are affected. Not even the birthday reminder, that only shows on certain days, like the other affected icons. So some of the icons seem to unload correctly while others don't.

I believe some of the icons (specifically the birthday icon) are wrapped in PerScreen as well, so it makes sense to me that they'd only show once for the screen (I think). Things like the Travelling Merchant aren't. It's another inconsistency I'm hoping to address in the future

**Comment by drewhoener** [comment]
Hi @laszlostark could you try out v2.3.0 that I just released? I've been trying to replicate it for a while now and I just can't.
I'm wondering if I fixed it by mistake

**Comment by laszlostark** [comment]
@drewhoener Sadly the patch does not fix the issue for me. I did some more investigating and as it turns out, the weird behavior is only present on the Linux version of the game. That's my bad for forgetting to mention I'm on Linux, sorry.
Either way, I tried this on a Windows installation and failed to recreate the issue there. So it appears to be some kind of Linux/Windows inconsistency. I wonder if MacOS versions would be affected as well but I don't have a device to test that on.

**Comment by drewhoener** [comment]
Master is the same as v2.3.0 that I released last night. Did you compile it on windows or Linux? Maybe there's a difference?

**Comment by laszlostark** [comment]
I compiled on Linux by running ```dotnet build -c Release```
It spits out a bunch of warnings about nullability but the build finishes just fine (tried dotnet-sdk versions 6.0.128 and 8.0.103 which both worked)

I also just tried compiling on Windows with dotnet 6.0.128 and 8.0.203 which both had the issue present again when I tested the build on Linux.

**Comment by drewhoener** [comment]
I almost wish it didn't compile, since at least then I could debug on Linux, but it actually works...
I'll try and throw together a debugger version that spits some stuff into the console I guess?

**Comment by laszlostark** [comment]
@drewhoener I've found the issue! For some reason the ```assets``` folder in the release is entirely lower case. The mod however expects the leading A to be capitalized. Linux filepaths are case sensitive so SMAPI throws an error, both when loading a save and when quitting the game. This seems to somehow screw with the unloading of the icons.

When I built the project on Linux, the ```Assets``` folder was formatted properly. When I built it on Windows, for whatever reason, the leading A was not capitalized.

**Comment by drewhoener** [comment]
Huh, does that actually fix the issue???

**Comment by laszlostark** [comment]
@drewhoener It does, I renamed the assets folder in the v2.3.0 release to Assets and the issue is gone.

My guess is that SMAPI stops some of the mod's code from executing once the error is thrown, which then results in icons not being properly unloaded.

**Comment by laszlostark** [comment]
SMAPI throws the error when the mod tries to dispose of the experienceBar, because of a NullReferenceException (the missing level up sound I suppose). Looking at `_elementsToDispose` in `ModOptionsPageHandler.cs` the items positioned after `experienceBar` in the list about match, which items will be duplicated when loading a new save.

```c#
_elementsToDispose = new List<IDisposable>
{
  luckOfDay,
  showBirthdayIcon,
  showAccurateHearts,
  locationOfTownsfolk,
  showWhenAnimalNeedsPet,
  showCalendarAndBillboardOnGameMenuButton,
  showCropAndBarrelTime,
  experienceBar,
  showItemHoverInformation,
  showTravelingMerchant,
  showRainyDayIcon,
  shopHarvestPrices,
  showQueenOfSauceIcon,
  showToolUpgradeStatus,
  showRobinBuildingStatusIcon,
  showSeasonalBerry
};
```

**Comment by drewhoener** [comment]
@laszlostark could you upload the log to https://smapi.io/log? I'm trying to figure out what to do about the path. If it expects lower-case assets, I should probably just change the code to that

**Comment by drewhoener** [comment]
@laszlostark After asking around, apparently it's just a build system thing. I've renamed the assets folder to be lowercase, and changed the ExperienceBar to match.
Would you mind just checking the build before I post it?
[UIInfoSuite2_2.3.0_assets_hotfix.zip](https://github.com/Annosz/UIInfoSuite2/files/14702393/UIInfoSuite2_2.3.0_assets_hotfix.zip)

**Comment by laszlostark** [comment]
@drewhoener Tested it, works just fine. No more errors or duplicated icons. Thank you!

**Comment by drewhoener** [comment]
Thank you for all the help debugging! That sure was a weird one
